@extends('layouts.app')

@section('title', 'Sudoku Game')

@section('content')
    <div class="max-w-4xl mx-auto">
        <!-- Game Header -->
        <div class="bg-white rounded-t-xl p-6 border-b">
            <div class="flex justify-between items-center">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900">Sudoku</h1>
                    <p class="text-gray-600">Select difficulty and start playing!</p>
                </div>
                <div class="flex gap-3">
                    <select id="difficulty" class="border rounded-lg px-4 py-2">
                        <option value="easy">Easy</option>
                        <option value="medium">Medium</option>
                        <option value="hard">Hard</option>
                    </select>
                    <button onclick="startGame()" class="bg-yellow-500 text-white px-6 py-2 rounded-lg hover:bg-yellow-600 font-medium">
                        New Game
                    </button>
                </div>
            </div>
        </div>

        <!-- Timer and Stats -->
        <div id="game-stats" class="bg-gray-100 px-6 py-3 flex justify-around text-center hidden">
            <div>
                <div class="text-2xl font-bold text-gray-900" id="timer">00:00</div>
                <div class="text-xs text-gray-500">Time</div>
            </div>
            <div>
                <div class="text-2xl font-bold text-red-600" id="mistakes">0</div>
                <div class="text-xs text-gray-500">Mistakes</div>
            </div>
            <div>
                <div class="text-2xl font-bold text-blue-600" id="hints">0</div>
                <div class="text-xs text-gray-500">Hints</div>
            </div>
        </div>

        <!-- Sudoku Board -->
        <div class="bg-white p-6">
            <div id="sudoku-board" class="grid grid-cols-9 gap-0 border-2 border-gray-800 mx-auto max-w-md">
                <!-- Cells will be generated by JavaScript -->
            </div>
        </div>

        <!-- Number Pad -->
        <div class="bg-white rounded-b-xl p-6 border-t">
            <div class="flex justify-center gap-2">
                @for($i = 1; $i <= 9; $i++)
                    <button onclick="selectNumber({{ $i }})" 
                            class="w-12 h-12 bg-gray-200 hover:bg-gray-300 rounded-lg font-bold text-xl">
                        {{ $i }}
                    </button>
                @endfor
                <button onclick="selectNumber(0)" class="w-12 h-12 bg-red-200 hover:bg-red-300 rounded-lg font-bold text-xl">
                    ✕
                </button>
            </div>
        </div>

        <!-- Leaderboard Link -->
        <div class="mt-6 text-center">
            <a href="{{ route('leaderboard') }}" class="text-yellow-600 hover:text-yellow-700 font-medium">
                View Leaderboard →
            </a>
        </div>
    </div>

    <script>
        let currentGame = null;
        let selectedCell = null;
        let startTime = null;
        let timerInterval = null;

        function startGame() {
            const difficulty = document.getElementById('difficulty').value;
            
            fetch('/game/start', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                body: JSON.stringify({ difficulty })
            })
            .then(response => response.json())
            .then(data => {
                currentGame = data;
                renderBoard(data.puzzle);
                startTimer();
                document.getElementById('game-stats').classList.remove('hidden');
            });
        }

        function renderBoard(puzzle) {
            const board = document.getElementById('sudoku-board');
            board.innerHTML = '';

            for (let i = 0; i < 9; i++) {
                for (let j = 0; j < 9; j++) {
                    const cell = document.createElement('div');
                    const value = puzzle[i][j];
                    const isInitial = value !== 0;
                    
                    cell.className = `w-10 h-10 sm:w-12 sm:h-12 border flex items-center justify-center cursor-pointer 
                        ${isInitial ? 'bg-gray-100 font-bold' : 'bg-white hover:bg-yellow-50'} 
                        ${(j + 1) % 3 === 0 && j < 8 ? 'border-r-2 border-gray-800' : 'border'}
                        ${(i + 1) % 3 === 0 && i < 8 ? 'border-b-2 border-gray-800' : 'border'}`;
                    
                    cell.textContent = value || '';
                    cell.dataset.row = i;
                    cell.dataset.col = j;
                    
                    if (!isInitial) {
                        cell.onclick = () => selectCell(i, j);
                    }
                    
                    board.appendChild(cell);
                }
            }
        }

        function selectCell(row, col) {
            if (selectedCell) {
                selectedCell.classList.remove('bg-yellow-200');
            }
            selectedCell = document.querySelector(`[data-row="${row}"][data-col="${col}"]`);
            selectedCell.classList.add('bg-yellow-200');
        }

        function selectNumber(num) {
            if (!selectedCell) return;
            
            const row = selectedCell.dataset.row;
            const col = selectedCell.dataset.col;

            fetch(`/game/${currentGame.game_id}/validate`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                body: JSON.stringify({ row: parseInt(row), col: parseInt(col), value: num })
            })
            .then(response => response.json())
            .then(data => {
                if (data.valid) {
                    selectedCell.textContent = num || '';
                    selectedCell.classList.remove('bg-yellow-200', 'bg-white');
                    selectedCell.classList.add('bg-gray-100', 'font-bold');
                    selectedCell = null;

                    if (data.is_complete) {
                        completeGame();
                    }
                } else {
                    // Show wrong answer
                    selectedCell.classList.add('bg-red-200');
                    document.getElementById('mistakes').textContent = 
                        parseInt(document.getElementById('mistakes').textContent) + 1;
                }
            });
        }

        function startTimer() {
            startTime = Date.now();
            timerInterval = setInterval(() => {
                const elapsed = Math.floor((Date.now() - startTime) / 1000);
                const mins = Math.floor(elapsed / 60).toString().padStart(2, '0');
                const secs = (elapsed % 60).toString().padStart(2, '0');
                document.getElementById('timer').textContent = `${mins}:${secs}`;
            }, 1000);
        }

        function completeGame() {
            clearInterval(timerInterval);
            const timeSeconds = Math.floor((Date.now() - startTime) / 1000);
            const mistakes = parseInt(document.getElementById('mistakes').textContent);
            const hints = parseInt(document.getElementById('hints').textContent);

            fetch(`/game/${currentGame.game_id}/complete`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                body: JSON.stringify({ time_seconds: timeSeconds, mistakes, hints_used: hints })
            })
            .then(response => response.json())
            .then(data => {
                alert(`Congratulations! Score: ${data.score}`);
            });
        }
    </script>
@endsection